export const Appetizers = [
    {
        id: 1,
        title: 'Calamari',
        category: 'Appetizer',
        price: 12.99,
        img: 'https://basilandbubbly.com/wp-content/uploads/2021/04/fried-calamari-6-500x500.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget. `,
    },
    {
        id: 2,
        title: 'Crispy Wings',
        category: 'Appetizer',
        price: 13.99,
        img: 'https://www.umami.site/wp-content/uploads/2021/03/crispy-baked-chicken-wing-recipe.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget. `,
    },
    {
        id: 3,
        title: 'Mozzarella Sticks',
        category: 'Appetizer',
        price: 8.99,
        img: 'https://www.dinneratthezoo.com/wp-content/uploads/2019/12/mozzarella-sticks-4.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget. `,
    },
    {
        id: 4,
        title: 'Queso Dip',
        category: 'Appetizer',
        price: 10.99,
        img: 'https://dfbkuy5licyr9.cloudfront.net/wp-content/uploads/2020/11/Not-Really-Chilis-Queso-Dip.jpg?x29550',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
    {
        id: 5,
        title: 'Guacamole & Chips ',
        category: 'Appetizer',
        price: 13.99,
        img: 'https://foodhub.scene7.com/is/image/woolworthsltdprod/guacamole-with-tortilla-chips:Square-1300x1300',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    }
]

export const Salad = [
    {
        id: 1,
        title: 'Ceasar Salad',
        category: 'Salad',
        price: 12.99,
        img: 'https://www.jessicagavin.com/wp-content/uploads/2019/07/caesar-salad-10-1200.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget. `,
    },
    {
        id: 2,
        title: 'Thai Salad',
        category: 'Salad',
        price: 14.99,
        img: 'https://www.culinaryhill.com/wp-content/uploads/2021/05/Rainbow-Thai-Salad-with-Mango-Culinary-Hill-1200x800-1.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.  `,
    },
    {
        id: 3,
        title: 'House Salad*',
        category: 'Salad',
        price: 10.99,
        img: 'https://letsdishrecipes.com/wp-content/uploads/2021/06/Loaded-House-Salad-feature.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    }
]
export const Pizza = [
    {
        id: 1,
        title: 'Margherita Pizza',
        category: 'Pizza',
        price: 20.99,
        img: 'https://lilluna.com/wp-content/uploads/2020/12/margherita-pizza-resize-3.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget. `,
    },
    {
        id: 2,
        title: 'Pepperoni Pizza',
        category: 'Pizza',
        price: 22.99,
        img: 'https://www.cookingclassy.com/wp-content/uploads/2014/07/pepperoni-pizza6+srgb..jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget. `,
    },
    {
        id: 3,
        title: 'Truffle Mushroom Pizza',
        category: 'Pizza',
        price: 26.99,
        img: 'https://www.foodiecrush.com/wp-content/uploads/2018/05/Truffle-Mushroom-Pizza-foodiecrush.com-017.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget..`,
    },
    {
        id: 4,
        title: 'Italian Sausage Pizza ',
        category: 'Pizza',
        price: 18.99,
        img: 'https://myfoodbook.com.au/sites/default/files/styles/schema_img/public/recipe_photo/Brev20145421_0.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget. `,
    },
    {
        id: 5,
        title: 'Vegan Pizza',
        category: 'Pizza',
        price: 12.99,
        img: 'https://www.goodlifeeats.com/wp-content/uploads/2022/06/Vegetarian-Pizza-720x720.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
]

export const Entree = [
    {
        id: 1,
        title: 'Italian Sausage Potato Lasagna ',
        category: 'Entree',
        price: 24.99,
        img: 'https://wildflourskitchen.com/wp-content/uploads/2016/02/potato-lasagna.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
    {
        id: 2,
        title: 'Seared Salmon',
        category: 'Entree',
        price: 28.99,
        img: 'https://i0.wp.com/fountainavenuekitchen.com/wp-content/uploads/2022/03/FAK_022322_Salmon-0028.jpeg?fit=2000%2C1334&ssl=1',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget. `,
    },
    {
        id: 3,
        title: 'Duck Confit ',
        category: 'Entree',
        price: 26.99,
        img: 'https://www.prairiefarms.com/wp-content/uploads/2020/03/Duck-Leg-Confit.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.  `,
    },
    {
        id: 4,
        title: 'Cioppino',
        category: 'Entree',
        price: 28.99,
        img: 'https://www.seriouseats.com/thmb/Du5iV_rzlfVS_y3xZIuKYbAacOM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20211201-cioppino-vicky-wasik-35-442bc0d48eec4e3fa2529f42e52797a8.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
    {
        id: 5,
        title: 'Spicy Chicken Cacciatore',
        category: 'Entree',
        price: 24.99,
        img: 'https://recipetineats.com/wp-content/uploads/2017/10/Spicy-Italian-Chicken-2-landscape.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget. `,
    },
    {
        id: 6,
        title: 'Roasted Beef Tenderloin',
        category: 'Entree',
        price: 38.99,
        img: 'https://static01.nyt.com/images/2022/12/21/multimedia/15korex1-tenderloin-1-63ce/15korex1-tenderloin-1-63ce-mediumSquareAt3X.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget. `,
    },
]

export const Sides = [
    {
        id: 1,
        title: 'Cajun Fries',
        category: 'Sides',
        price: 8.99,
        img: 'https://www.girlgonegourmet.com/wp-content/uploads/2020/06/Cajun-French-Fries-5.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget..`,
    },
    {
        id: 2,
        title: 'Potato Tots',
        category: 'Sides',
        price: 10.99,
        img: 'https://www.micadeli.com/wp-content/uploads/2019/11/vegan-potato-tots-tatar-micadeli.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget. `,
    },
    {
        id: 3,
        title: 'Side Salad',
        category: 'Sides',
        price: 6.99,
        img: 'https://www.9010nutrition.com/wp-content/uploads/2019/01/side-salad-1.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
]


export const Beverages = [
    {
        id: 1,
        title: 'Sprite',
        category: 'Beverages',
        price: 2.99,
        img: 'https://s7d1.scene7.com/is/image/mcdonalds/Header_MediumSprite_Glass_832x472:1-3-product-tile-desktop?wid=765&hei=472&dpr=off',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
    {
        id: 2,
        title: 'Coke',
        category: 'Beverages',
        price: 2.99,
        img: 'https://s7d1.scene7.com/is/image/mcdonalds/DC_202112_0521_MediumCoke_Glass_832x472:1-3-product-tile-desktop?wid=765&hei=472&dpr=off',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget. `,
    },
    {
        id: 3,
        title: 'Diet Coke',
        category: 'Beverages',
        price: 2.99,
        img: 'https://cdn.mos.cms.futurecdn.net/oRRY7oSEyFyfA7kpRRFPoT.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.  `,
    },
    {
        id: 4,
        title: 'Apple Juice',
        category: 'Beverages',
        price: 3.99,
        img: 'https://minnetonkaorchards.com/wp-content/uploads/2022/06/Apple-Juice-Benefits-5.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
    {
        id: 5,
        title: 'Orange Juice',
        category: 'Beverages',
        price: 3.99,
        img: 'https://media.glamour.com/photos/612d343de274243a3defbc8f/master/w_2560%2Cc_limit/1225546255',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.  `,
    },
    {
        id: 6,
        title: 'House Tea',
        category: 'Beverages',
        price: 1.99,
        img: 'https://www.rappler.com/tachyon/2019/09/Screen-Shot-2022-05-17-at-4.42.48-PM.png',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
    {
        id: 7,
        title: 'Sparking Water',
        category: 'Beverages',
        price: 2.99,
        img: 'https://beverages2u.com/wp-content/uploads/2020/01/san-pellegrino-33-oz-bottle-scaled.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.  `,
    },
]

export const Cocktails = [
    {
        id: 1,
        title: 'House Margarita',
        category: 'Cocktails',
        price: 16.99,
        img: 'https://elmatadorrestaurant.com/wp-content/uploads/2020/07/House-Margarita-1.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
    {
        id: 2,
        title: 'Gin & Tonic',
        category: 'Cocktails',
        price: 14.99,
        img: 'https://www.liquor.com/thmb/hqV-5sV5FNsTKzU1gXzEp0oc9yw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__liquor__2017__07__13091447__spanish-gin-and-tonic-720x720-recipe-c700052505244cdcb95f241131870e42.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.  `,
    },
    {
        id: 3,
        title: 'Martini',
        category: 'Cocktails',
        price: 16.99,
        img: 'https://amandascookin.com/wp-content/uploads/2022/03/Dirty-Martini-RC-SQ.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
    {
        id: 4,
        title: 'Old Fashion',
        category: 'Cocktails',
        price: 15.99,
        img: 'https://cdn.shopify.com/s/files/1/0416/5599/2469/files/old-fashioned-classic-recipe.png?v=1659714695',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.  `,
    },
    {
        id: 5,
        title: 'Mint Mojito',
        category: 'Cocktails',
        price: 16.99,
        img: 'https://www.shakedrinkrepeat.com/wp-content/uploads/2021/08/mojito-8.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
]

export const Wines = [
    {
        id: 1,
        title: 'House Red',
        category: 'Red/Whites',
        price: 12.99,
        img: 'https://www.foodandwine.com/thmb/B6XvMMR6r9OcAETGgp2ypqK_-wI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/red-wine-blends-FT-MAG1116-2000-4f3c3e91bcd646ea8a21f2152746ef53.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.  `,
    },
    {
        id: 2,
        title: 'House White',
        category: 'Red/Whites',
        price: 12.99,
        img: 'https://pizzaonne.com/wp-content/uploads/2018/04/white-wine-social.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
    {
        id: 3,
        title: 'Pinot Nior',
        category: 'Red/Whites',
        price: 15.99,
        img: 'https://i0.wp.com/www.thegourmetshop.net/wp-content/uploads/blog-wine-4.png?fit=540%2C540&ssl=1',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.  `,
    },
    {
        id: 4,
        title: 'Cabernet Sauvignon ',
        category: 'Red/Whites',
        price: 16.99,
        img: 'https://e5ftmhav2q3.exactdn.com/wp-content/uploads/2022/03/product-featured-paso-cab-768x768.jpg?strip=all&lossy=1&ssl=1',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
    {
        id: 5,
        title: 'Chardonnay',
        category: 'Red/Whites',
        price: 15.99,
        img: 'https://www.foodandwine.com/thmb/rstJ74eFEsG15noDsZA-R3n9hvI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Chardonnay-Under-15-FT-BLOG0322-ea0592e5377b4f87a4e2c7d36f3496f6.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
    {
        id: 6,
        title: 'Rosé',
        category: 'Red/Whites',
        price: 16.99,
        img: 'https://images.wineselectors.com.au/media/wineselectors/blog/wine/rose-hero.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },

]

export const Desserts = [
    {
        id: 1,
        title: 'Lemonchello Mousse',
        category: 'Desserts',
        price: 16.99,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBInWNnd2MoXhdjqzG1e2FZk7fd4Pxe55OyA&usqp=CAU',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
    {
        id: 2,
        title: 'New York Cheesecake',
        category: 'Desserts',
        price: 15.99,
        img: 'https://tornadoughalli.com/wp-content/uploads/2018/09/NEW-YORK-STYLE-CHEESECAKE2-2.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
    {
        id: 3,
        title: 'Crème brûlée',
        category: 'Desserts',
        price: 12.99,
        img: 'https://simplyhomecooked.com/wp-content/uploads/2023/01/creme-brulee-recipe-6.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
    {
        id: 4,
        title: 'Raspberry Coconut Parfait',
        category: 'Desserts',
        price: 13.99,
        img: 'https://realfood.tesco.com/media/images/RFO-1400x919-Parfait-e5d0d3f3-3ca3-4bbd-84e3-3a1a7a94cec5-0-1400x919.jpg',
        desc: `Lorem ipsum dolor sit amet consectetur. At varius purus in varius pharetra ut maecenas eget.`,
    },
]